apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployment-bot.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default "argocd" }}
  labels:
    {{- include "deployment-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $value := .Values.deployment_bot.secrets }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end}}
  {{- end }}
